uniqueHomePage = true # change to false to add sidebar to homepage

enableDarkMode = false # set to false to disable darkmode by default # user will still have the option to use dark mode
defaultLightingMode = "auto" # other possible values: "dark", "light"

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 10

# show/hide line numbers by default. Switch to `true` if you'd rather have them on.
showLineNumbers = false

# Defaults to true if not set
# Enable copyRight Footer Stamp. Takes in attribution
enableCopyright = false

# search
[search]
on = false
global = false 

# Site logo
[logo]
  lightMode = "images/logoweb.png"
  darkMode = "images/logoweb.png"

[source]
  name = "GitHub"
  iconLight = "images/GitHubMarkLight.svg"
  iconDark = "images/GitHubMarkDark.svg"
  url = "https://github.com/Blade-OS"